name: "Release-Draft"

on:
  push:
    branches: [ main ]

jobs:
  Release-Draft:
    name: "Release-Draft"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          draft: true
          title: "Links Extractor pre-release"
          files: |
